### ISSUE TITLE
E2E Testing

### ISSUE THREAD

**Issue by ValerianClerc** [Compete-McGill/wisp#10]
Testing the entire functionality of the application.

@ahmed-elehwany 's specialty.

**Comment by ahmed-elehwany** [comment]
Created setup for e2e manual testing using nightwatch and selenium.
Created test demo example for login and home pages.
Created ToDos for other pages e2e expected functionalities.

Testing requirements:
- Chrome version: "^83.0.0"
(for now tests are run manually, but once we support CI and create a docker image that has the right browser/driver version for e2e tests, we should be fine, I believe.

To run tests:
- npm run e2e
