### ISSUE TITLE
[STORY] Unit Testing

### ISSUE THREAD

**Issue by ValerianClerc** [Compete-McGill/wisp#11]
Backend repositories need unit testing.

TODO:
- Set up unit testing framework/environment on:
     - [x] wisp-users-microservice
     - [x] wisp-problems-microservice
- Write full unit tests on:
     - [x] wisp-users-microservice
     - [x] wisp-problems-microservice

**Comment by MohamedBeydoun** [comment]
@MohamedBeydoun will test wisp-users
@ValerianClerc will test wisp-problem
