### ISSUE TITLE
CI/CD Improvements: Add linting to git pre-commit hook

### ISSUE THREAD

**Issue by ValerianClerc** [Compete-McGill/wisp#7]
Commits are being pushed without being linted, and it's annoying for the developers to have to run lint every time. We should add lint commands to the git precommit hooks on each repo.

Currently:
* `wisp-ui` linting step both checks linting and makes linting changes?
* `wisp-problems-microservice` and `wisp-problems-microservice` linters aren't fully set up and configured?

What we want:
- [x] pre-lint hook before each commit to check linting + make linting changes.
- [x] CI action to ONLY check linting (don't make linting changes), and fail the build if linting isn't good.

**Comment by MohamedBeydoun** [comment]
Done in wisp-ui
